server {
    # listen 80: Nginx escucha en el puerto HTTP estándar
    listen 80;
    
    # server_name localhost: Acepta cualquier solicitud que llegue a la máquina
    server_name localhost;

    # root: Ruta del disco del contenedor donde copiamos los archivos de Angular
    root /usr/share/nginx/html;
    
    # index: El archivo inicial que debe cargar el navegador
    index index.html;

    location / {
        # try_files: Intenta buscar el archivo solicitado; si no existe, entrega index.html
        # Esto es FUNDAMENTAL para que rutas como /dashboard o /login no den 404 al recargar
        try_files $uri $uri/ /index.html;
    }

    # Habilitar compresión Gzip para que la página cargue ultra rápido en la nube
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
