server:
  port: 8082

spring:
  application:
    name: carrito-api
  datasource:
    url: jdbc:mysql://pedidos360-db.cmce5dstqmg9.us-east-1.rds.amazonaws.com:3306/pedidos360?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Ayuwoki15.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

azure:
  tenant-id: e5372bf0-c5e3-4286-887c-79069f209c1f
  client-id: 0d5904de-0d7a-474d-ba0a-d8a8ea6d14f8
  expected-audience: 0d5904de-0d7a-474d-ba0a-d8a8ea6d14f8
  issuer-v2: https://login.microsoftonline.com/e5372bf0-c5e3-4286-887c-79069f209c1f/v2.0

cors:
  allowed-origins: http://localhost:5173,http://localhost:4200,https://z97t6a0hfj.execute-api.us-east-1.amazonaws.com

# TEMPORAL: para ver el motivo exacto de un 401 mientras depuramos.
logging:
  level:
    org.springframework.security: DEBUG
